name: shared_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0


dev_dependencies:
  drift_dev: ^2.0.0
  build_runner: ^2.0.0
  lints: ^3.0.0
  test: ^1.24.0
