name: shared_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  drift: 2.26.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0


dev_dependencies:
  drift_dev: 2.26.1
  build_runner: ^2.4.15
  lints: ^3.0.0
  test: ^1.25.8
